routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->check())
        return redirect()->route('dashboard.index');

    return redirect()->route('login');
});

/**
 * AUTHENTICATION ROUTES
 */
Auth::routes();

/**
 * PAGES ROUTES
 */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

/**
 * ROTAS DE CADASTRO
 */

// Clientes
Route::resource('clientes', 'ClienteController');

// Profissionais
Route::resource('profissionais', 'ProfissionalController');

// Serviços
Route::resource('servicos', 'ServicoController');

// Produtos
Route::resource('produtos', 'ProdutoController');

// Pacotes
Route::resource('pacotes', 'PacoteController');

// Comandas
Route::resource('comandas', 'ComandaController');

/**
 * ROTAS DA AGENDA
 */
Route::prefix('agenda')->group(function() {

    Route::get('', 'AgendaController@index')->name('agenda.index');
    Route::get('/calendario', 'AgendaController@calendario')->name('agenda.calendario');
    Route::get('/novo-agendamento', 'AgendaController@novoAgendamento')->name('agenda.novoAgendamento');

});

/**
 * ROTAS DE AGENDAMENTO
 */
Route::resource('agendamentos', 'AgendamentoController');

/**
 * ROTAS DE AJAX
 */
Route::namespace('Ajax')->prefix('ajax')->group(function() {

    // Clientes
    Route::post('/modalInformacoesCliente', 'AjaxController@modalInformacoesCliente');

    // Profissionais
    Route::post('/modalInformacoesProfissional', 'AjaxController@modalInformacoesProfissional');

    // Serviços
    Route::post('/modalInformacoesServico', 'AjaxController@modalInformacoesServico');

    // Pacote
    Route::post('/modalInformacoesPacote', 'AjaxController@modalInformacoesPacote');
    
    // Agenda
    Route::post('/profissionaisDeUmServico', 'AjaxController@profissionaisDeUmServico');
    Route::post('/recuperarClientes', 'AjaxController@recuperarClientes');
    Route::post('/modalAgendamento', 'AjaxController@modalAgendamento');
    Route::post('/horariosDisponiveisDeUmProfissional', 'AjaxController@horariosDisponiveisDeUmProfissional');
    Route::post('/realizarAgendamento', 'AjaxController@realizarAgendamento');

});

use App\Agendamento;
use App\Profissional;
use App\Servico;
use Carbon\Carbon;

Route::get('/teste', function() {

    $idProfissional = 4;
    $idServico = 7;
        
    /**
     * Cria um vetor de horas (https://surniaulula.com/2016/lang/php/php-create-an-array-of-hours/)
     */
    function get_hours_range( $start = 0, $end = 86400, $step = 3600, $format = 'g:i a', $boolean = true ) {
        $times = array();
        for ( $i = 0; $i <= 6; $i++ ) { 
            foreach ( range( $start, $end, $step ) as $timestamp ) {
                $hour_mins = gmdate( 'H:i', $timestamp );
                $times[$i][$hour_mins] = $boolean;
            }
        }
        return $times;
    }

    /**
     * Recupera o inicio dessa semana
     */
    function primeiroDiaSemana($week, $year) {
        $dto = new DateTime();
        $dto->setISODate($year, $week);
        return $dto;
    }

    // Lista de horários das 10:00 às 18:00
    $horariosSemana = get_hours_range(36000, 64800, 900, 'g:i a', true);
    $limite = DateTime::createFromFormat('H:i', '18:00');

    // Lista de agendamentos
    $agendamentos = Agendamento::where('id_profissional', $idProfissional)->get();

    // Retorna apenas os agendamentos da semana atual
    $agendamentos = $agendamentos->filter(function($ag) {
        $inicio = new DateTime($ag->inicio);
        $semana = $inicio->format('W');
        $essaSemana = date('W');
        return $semana == $essaSemana; 
    });

    /**
     * Primeiro loop para marcar horários ocupados
     */
    foreach ($agendamentos as $ag) {
        
        $inicio = new DateTime($ag->inicio);    // DateTime de início do agendamento
        $fim = new DateTime($ag->fim);          // DateTime de fim do agendamento
        $dia = $inicio->format('N') - 1;        // Representação numérica do dia da semana (0: Segunda, 1: Terça,..., 5: Sábado, 6: Domingo)

        $atual = clone $inicio;
        while ($atual <= $fim) {
            $horario = $atual->format("H:i");
            $horariosSemana[$dia][$horario] = false;      // Marca o horário como ocupado
            $atual->modify("+15 minutes");          // Avança 15 minutos
        }

    }

    $tempo_execucao = Servico::find($idServico)->tempo_execucao_em_minutos;
    $horariosDisponiveis = get_hours_range(36000, 64800, 900, 'g:i a', false);

    /**
     * Segundo loop para verificar disponibilidade
     */
    foreach ($horariosSemana as $dia => $horarios) {
        foreach ($horarios as $horario => $disponivel) {
            
            $atual = DateTime::createFromFormat('H:i', $horario);
            $hAtual = $atual->format('H:i');
            $fim = clone $atual;
            $fim->modify("+" . $tempo_execucao . " minutes");
            $hFim = $fim->format('H:i');

            /**
             * Verifica se o horário atual está disponível e o horário depois do tempo
             * de execução do serviço está disponível. Se sim, este é um horário disponível
             */
            if ($horariosSemana[$dia][$hAtual] == true AND $fim <= $limite AND $horariosSemana[$dia][$hFim] == true) {
                $horariosDisponiveis[$dia][$hAtual] = true;
            }
        }
    }

    // Dias da semana
    $segunda = primeiroDiaSemana(date('W'), date('Y'));

    return view('dashboard.agenda.tabela-horarios-disponiveis', [
        'horariosDisponiveis' => $horariosDisponiveis,
        'segunda' => $segunda,
    ]);

});

app/Pacote.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pacote extends Model
{
    //
    public function servicos() {
        return $this->belongsToMany('App\Servico', 'pacote_servico', 'id_pacote', 'id_servico');
    }
}

app/Http/Controllers/PacoteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Servico;
use App\Pacote;
use App\Traits\WhatsappTrait;

class PacoteController extends Controller
{
    use WhatsappTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.cadastros.pacotes.index', [
            'pacotes' => Pacote::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.cadastros.pacotes.create', [
            'pacote' => new Pacote,
            'servicos' => Servico::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /**
         * Cria novo pacote
         */
        $pacote = new Pacote;
        $pacote->nome = request('nome');

        $servicos = request('servicos');
        $pacote->valor_sem_desconto = request('valor-sem-desconto');
        $pacote->desconto = request('desconto');
        $pacote->valor_com_desconto = request('valor-com-desconto');
        $pacote->descricao = request('descricao');
        $pacote->ativo = request('ativo') == 'on' ? true : false;
        $pacote->save();

        /**
         * Atribui os servicos
         */
        $pacote->servicos()->sync(request('servicos'));

        /**
         * Envia uma notificação por whatsapp
         */
        if ($pacote->ativo)
            $this->enviarWhatsappPacote($pacote);

        return redirect()->route('pacotes.index')->with('success', 'Pacote cadastrado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Recupera o pacote
        $pacote = Pacote::find($id);

        
        // Recupera os serviços
        $servicosSelecionados = array();
        foreach ($pacote->servicos->toArray() as $servico) {
            array_push($servicosSelecionados, $servico['id']);
        }
        
        return view('dashboard.cadastros.pacotes.edit', [
            'pacote' => $pacote,
            'servicos' => Servico::all(),
            'servicosSelecionados' => $servicosSelecionados,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**
         * Atualiza o pacote
         */
        $pacote = Pacote::find($id);
        $pacote->nome = request('nome');

        $servicos = request('servicos');
        $pacote->valor_sem_desconto = request('valor-sem-desconto');
        $pacote->desconto = request('desconto');
        $pacote->valor_com_desconto = request('valor-com-desconto');
        $pacote->descricao = request('descricao');
        $pacote->ativo = request('ativo') == 'on' ? true : false;
        $pacote->save();

        /**
         * Atribui os servicos
         */
        $pacote->servicos()->sync(request('servicos'));

        return redirect()->route('pacotes.index')->with('success', 'Pacote atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pacote = Pacote::find($id);
        $pacote->delete();

        return redirect()->route('pacotes.index')->with('success', 'Pacote removido com sucesso');
    }
}

resources/views/dashboard/cadastros/pacotes/_form.blade.php
<div class="row mt-5">
    <div class="col-6">
        <h5 class="mb-3">Informações Básicas</h5>

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do pacote" autocomplete="new" required value="{{ $pacote->nome }}">
        </div>

        <div class="form-group">
            <label for="servicos">Serviços</label>
            <select class="browser-default custom-select" id="servicos" name="servicos[]" multiple="multiple" required>
                @foreach ($servicos as $servico)
                    <option value="{{ $servico->id }}" data-preco-servico="{{ $servico->preco }}">{{ $servico->nome }}</option>
                @endforeach
            </select>
        </div>
        
        <div class="form-group">
            <label for="valor-sem-desconto">Valor (sem Desconto)</label>
            <input type="number" class="form-control" id="valor-sem-desconto" name="valor-sem-desconto" autocomplete="new" placeholder="Valor sem Desconto" readonly required value="{{ $pacote->valor_sem_desconto }}">
        </div>

        <div class="row">
            
            <div class="col">
                <div class="form-group">
                    <label for="valor-com-desconto">Valor (com Desconto)</label>
                    <input type="number" min="1" step="0.01" class="form-control" id="valor-com-desconto" name="valor-com-desconto" autocomplete="new" placeholder="Valor com Desconto" required value="{{ $pacote->valor_com_desconto }}">
                </div>
            </div>

            <div class="col">
                <div class="form-group">
                    <label for="desconto">Desconto (%)</label>
                    <input type="number" min="1" max="100" step="0.01" class="form-control" id="desconto" name="desconto" placeholder="Desconto" autocomplete="new" required value="{{ $pacote->desconto }}">
                </div>
            </div>
            
            
        </div>

        <div class="form-group">
            <label for="descricao">Descrição</label>
            <textarea class="form-control rounded-1" id="descricao" rows="3" placeholder="Descrição sobre o pacote" name="descricao" value="{{ $pacote->descricao }}"></textarea>
        </div>

        <label class="d-block mt-3">O pacote está ativo?</label>
        <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="ativo" name="ativo" {{ $pacote->ativo ? 'checked' : '' }} >
            <label class="custom-control-label" for="ativo"></label>
        </div>


    </div>
    
</div>

resources/views/dashboard/cadastros/pacotes/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('pacotes.store') }}">
        @csrf

        <h3>Cadastro de Pacotes</h3>
        
        @include('dashboard.cadastros.pacotes._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Cadastrar</button>
    </form>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/pacote/create.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/pacotes/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('pacotes.update', $pacote->id) }}">
        @method('PUT')
        @csrf

        <h3>Edição do Pacote ({{ $pacote->nome }})</h3>
        
        @include('dashboard.cadastros.pacotes._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Editar</button>
    </form>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/pacote/create.js') }}"></script>
    <script>
        $(document).ready(function() {
           
            // Pre seleciona os servicos
            $('#servicos').val(@json($servicosSelecionados)).trigger('change');

        });
    </script>
@endsection

resources/views/dashboard/cadastros/pacotes/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <div class="d-flex justify-content-between w-100">
        <div>
            <h3>Pacotes</h3>
            <p>Número de Pacotes:  {{ count($pacotes) }} </p>
        </div>
        <div>
            <a href="{{ route('pacotes.create') }}" class="btn btn-light btn-tool add">Adicionar um Pacote</a>
        </div>
    </div>

    @if (count($pacotes) > 0)
        <table class="table table-cadastro">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Ativo</th>
                    <th>Preço</th>
                    <th>Serviços</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($pacotes as $pacote)
                    <tr>
                        <td>{{ $pacote->nome }}</td>
                        <td>{{ $pacote->ativo ? 'Sim' : 'Não' }}</td>
                        {{-- <td>{{ $pacote->valor_sem_desconto }}</td> --}}
                        {{-- <td>{{ $pacote->desconto }}</td> --}}
                        <td>{{ $pacote->valor_com_desconto }}</td>
                        <td>
                            @foreach ($pacote->servicos as $servico)
                                <span class="badge badge-light">{{ $servico->nome }}</span>
                            @endforeach    
                        </td>
                        <td class="td-actions">
                            <button class="btn-action view" data-id-pacote="{{ $pacote->id }}"><i class="fas fa-eye"></i></button>
                            <a href="{{ route('pacotes.edit', $pacote->id) }}" class="btn-action"><i class="fas fa-pencil-alt"></i></a>
                            <form method="POST" action="{{ route('pacotes.destroy', $pacote->id) }}" class="remove-form" onsubmit="return confirm('Você realmente quer remover este pacote?');">
                                @method('DELETE')
                                @csrf
                                <button class="btn-action"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-info" role="alert">
            Nenhum pacote foi cadastrado ainda. Você pode cadastrar um clicando no botão acima.
        </div>
    @endif

    <!-- Modal -->
    <div class="modal fade modal-view" id="modal-pacote" tabindex="-1" role="dialog" aria-labelledby="modal-pacote-label"
    aria-hidden="true">
        {{-- Preenchido com AJAX --}}
    </div>    


@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/pacote/index.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/pacotes/modal-pacote.blade.php
<div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-cliente-label"><span class="font-weight-bold">{{ $pacote->nome }}</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="">
                    <div class="row">

                        <div class="col">
                            <div class="desconto">
                                <img src="{{ asset('img/icons/desconto.png') }}">
                                <span class="valor">{{ $pacote->desconto }}%</span>
                            </div>
                        </div>
    
                        <div class="col-8">
                            <h5 class="header">Informações Básicas</h5>
                            <div class="row info">
                                    <div class="col-8 font-weight-bold">Preço sem Desconto</div>
                                    <div class="col">{{ $pacote->valor_sem_desconto }}</div>
                                </div>
                            <div class="row info mt-2">
                                <div class="col-8 font-weight-bold">Preço com Desconto</div>
                                <div class="col">{{ $pacote->valor_com_desconto }}</div>
                            </div>
                            <div class="row info mt-2">
                                <div class="col-8 font-weight-bold">Serviços</div>
                                <div class="col">
                                    @foreach ($pacote->servicos as $servico)
                                        <span class="badge badge-light">{{ $servico->nome }}</span>
                                    @endforeach 
                                </div>
                            </div>
                            <div class="row info mt-2">
                                <div class="col-8 font-weight-bold">Descrição</div>
                                <div class="col">{{ $pacote->descrição }}</div>
                            </div>

                        </div>       
                    
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>