routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->check())
        return redirect()->route('dashboard.index');

    return redirect()->route('login');
});

/**
 * AUTHENTICATION ROUTES
 */
Auth::routes();

/**
 * PAGES ROUTES
 */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

/**
 * ROTAS DE CADASTRO
 */

// Clientes
Route::resource('clientes', 'ClienteController');

// Profissionais
Route::resource('profissionais', 'ProfissionalController');

// Serviços
Route::resource('servicos', 'ServicoController');

// Produtos
Route::resource('produtos', 'ProdutoController');

// Pacotes
Route::resource('pacotes', 'PacoteController');

// Comandas
Route::resource('comandas', 'ComandaController');

/**
 * ROTAS DA AGENDA
 */
Route::prefix('agenda')->group(function() {

    Route::get('', 'AgendaController@index')->name('agenda.index');
    Route::get('/calendario', 'AgendaController@calendario')->name('agenda.calendario');
    Route::get('/novo-agendamento', 'AgendaController@novoAgendamento')->name('agenda.novoAgendamento');

});

/**
 * ROTAS DE AGENDAMENTO
 */
Route::resource('agendamentos', 'AgendamentoController');

/**
 * ROTAS DE AJAX
 */
Route::namespace('Ajax')->prefix('ajax')->group(function() {

    // Clientes
    Route::post('/modalInformacoesCliente', 'AjaxController@modalInformacoesCliente');

    // Profissionais
    Route::post('/modalInformacoesProfissional', 'AjaxController@modalInformacoesProfissional');

    // Serviços
    Route::post('/modalInformacoesServico', 'AjaxController@modalInformacoesServico');

    // Pacote
    Route::post('/modalInformacoesPacote', 'AjaxController@modalInformacoesPacote');
    
    // Agenda
    Route::post('/profissionaisDeUmServico', 'AjaxController@profissionaisDeUmServico');
    Route::post('/recuperarClientes', 'AjaxController@recuperarClientes');
    Route::post('/modalAgendamento', 'AjaxController@modalAgendamento');
    Route::post('/horariosDisponiveisDeUmProfissional', 'AjaxController@horariosDisponiveisDeUmProfissional');
    Route::post('/realizarAgendamento', 'AjaxController@realizarAgendamento');

});

use App\Agendamento;
use App\Profissional;
use App\Servico;
use Carbon\Carbon;

Route::get('/teste', function() {

    $idProfissional = 4;
    $idServico = 7;
        
    /**
     * Cria um vetor de horas (https://surniaulula.com/2016/lang/php/php-create-an-array-of-hours/)
     */
    function get_hours_range( $start = 0, $end = 86400, $step = 3600, $format = 'g:i a', $boolean = true ) {
        $times = array();
        for ( $i = 0; $i <= 6; $i++ ) { 
            foreach ( range( $start, $end, $step ) as $timestamp ) {
                $hour_mins = gmdate( 'H:i', $timestamp );
                $times[$i][$hour_mins] = $boolean;
            }
        }
        return $times;
    }

    /**
     * Recupera o inicio dessa semana
     */
    function primeiroDiaSemana($week, $year) {
        $dto = new DateTime();
        $dto->setISODate($year, $week);
        return $dto;
    }

    // Lista de horários das 10:00 às 18:00
    $horariosSemana = get_hours_range(36000, 64800, 900, 'g:i a', true);
    $limite = DateTime::createFromFormat('H:i', '18:00');

    // Lista de agendamentos
    $agendamentos = Agendamento::where('id_profissional', $idProfissional)->get();

    // Retorna apenas os agendamentos da semana atual
    $agendamentos = $agendamentos->filter(function($ag) {
        $inicio = new DateTime($ag->inicio);
        $semana = $inicio->format('W');
        $essaSemana = date('W');
        return $semana == $essaSemana; 
    });

    /**
     * Primeiro loop para marcar horários ocupados
     */
    foreach ($agendamentos as $ag) {
        
        $inicio = new DateTime($ag->inicio);    // DateTime de início do agendamento
        $fim = new DateTime($ag->fim);          // DateTime de fim do agendamento
        $dia = $inicio->format('N') - 1;        // Representação numérica do dia da semana (0: Segunda, 1: Terça,..., 5: Sábado, 6: Domingo)

        $atual = clone $inicio;
        while ($atual <= $fim) {
            $horario = $atual->format("H:i");
            $horariosSemana[$dia][$horario] = false;      // Marca o horário como ocupado
            $atual->modify("+15 minutes");          // Avança 15 minutos
        }

    }

    $tempo_execucao = Servico::find($idServico)->tempo_execucao_em_minutos;
    $horariosDisponiveis = get_hours_range(36000, 64800, 900, 'g:i a', false);

    /**
     * Segundo loop para verificar disponibilidade
     */
    foreach ($horariosSemana as $dia => $horarios) {
        foreach ($horarios as $horario => $disponivel) {
            
            $atual = DateTime::createFromFormat('H:i', $horario);
            $hAtual = $atual->format('H:i');
            $fim = clone $atual;
            $fim->modify("+" . $tempo_execucao . " minutes");
            $hFim = $fim->format('H:i');

            /**
             * Verifica se o horário atual está disponível e o horário depois do tempo
             * de execução do serviço está disponível. Se sim, este é um horário disponível
             */
            if ($horariosSemana[$dia][$hAtual] == true AND $fim <= $limite AND $horariosSemana[$dia][$hFim] == true) {
                $horariosDisponiveis[$dia][$hAtual] = true;
            }
        }
    }

    // Dias da semana
    $segunda = primeiroDiaSemana(date('W'), date('Y'));

    return view('dashboard.agenda.tabela-horarios-disponiveis', [
        'horariosDisponiveis' => $horariosDisponiveis,
        'segunda' => $segunda,
    ]);

});

resources/views/dashboard/cadastros/profissionais/_form.blade.php
<div class="row mt-5">

    <div class="col">
        <h5 class="mb-3">Contato</h5>

        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do profissional" autocomplete="new" required value="{{ $profissional->nome }}" value="{{ $profissional->nome }}">
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="cpf">CPF</label>
                    <input type="text" class="form-control" id="cpf" name="cpf" autocomplete="new" required value="{{ $profissional->cpf }}">
                </div>
            </div>

            <div class="col">
                <div class="form-group">
                    <label for="rg">RG</label>
                    <input type="text" class="form-control" id="rg" name="rg" placeholder="99.999.999-9" autocomplete="new" required value="{{ $profissional->rg }}">
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="tel-celular">Celular</label>
                    <input type="tel" class="form-control" id="tel-celular" name="tel-celular" placeholder="(15) 99999-9999" autocomplete="new" required value="{{ $profissional->telefone_celular }}">
                </div>
            </div>

            <div class="col">
                <div class="form-group">
                    <label for="tel-residencial">Residencial</label>
                    <input type="tel" class="form-control" id="tel-residencial" name="tel-residencial" placeholder="(15) 33333-3333" autocomplete="new" required value="{{ $profissional->telefone_residencial }}">
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Email do profissional" autocomplete="new" required value="{{ $profissional->email }}">
        </div>

        <h5 class="mt-4">Informações Adicionais</h5>

        <div class="form-group">
            <label for="servicos">Serviços</label>
            <select class="browser-default custom-select" id="servicos" name="servicos[]" multiple="multiple" required>
                @foreach ($servicos as $servico)
                    <option value="{{ $servico->id }}">{{ $servico->nome }}</option>
                @endforeach
            </select>
        </div>

    </div>

    <div class="col">

        <h5 class="mb-3">Endereço</h5>
        
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="cep">CEP</label>
                    <input type="text" class="form-control" id="cep" name="cep" placeholder="99999-999" autocomplete="new" required value="{{ $profissional->cep }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="cidade">Cidade</label>
                    <select class="browser-default custom-select" id="cidade" name="cidade" required>
                        <option></option>
                        @foreach ($cidades as $cidade)
                            <option value="{{ $cidade->id }}" {{ $profissional->cidade ? ($profissional->cidade->nome == $cidade->nome ? 'selected' : '') : '' }}>{{ $cidade->nome }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="bairro">Bairro</label>
                    <input type="text" class="form-control" id="bairro" name="bairro" placeholder="Bairro" autocomplete="new" required value="{{ $profissional->bairro }}">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="rua">Rua</label>
                    <input type="text" class="form-control" id="rua" name="rua" placeholder="Rua" autocomplete="new" required value="{{ $profissional->rua }}">
                </div>
            </div>
            <div class="col-5">
                <div class="form-group">
                    <label for="numero-rua">Número</label>
                    <input type="text" class="form-control" id="numero-rua" name="numero-rua" placeholder="Nº" autocomplete="new" required value="{{ $profissional->numero_rua }}">
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="complemento">Complemento</label>
            <input type="text" class="form-control" id="complemento" name="complemento" placeholder="Complemento" autocomplete="new" value="{{ $profissional->complemento_rua }}">
        </div>

        <h5 class="mt-4">Horário</h5>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label class="mt-3" for="horario-entrada">Entrada</label>
                    <input type="time" class="form-control" id="horario-entrada" name="horario-entrada" placeholder="Horário de entrada" autocomplete="new" required value="{{ $profissional->horario_entrada }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label class="mt-3" for="horario-saida">Saída</label>
                    <input type="time" class="form-control" id="horario-saida" name="horario-saida" placeholder="Horário de saída" autocomplete="new" required value="{{ $profissional->horario_saida }}">
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="color-picker">Cor para a agenda</label>
                    <input type='text' id="color-picker" name="cor-agenda" required value="{{ $profissional->cor_agenda }}">
                </div>
            </div>
        </div>

    </div>

    
</div>

resources/views/dashboard/cadastros/profissionais/create.blade.php
@extends('layouts.dashboard')


@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('profissionais.store') }}">
        @csrf

        <h3>Cadastro de Profissional</h3>
        
        @include('dashboard.cadastros.profissionais._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Cadastrar</button>
    </form>


@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/profissional/create.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/profissionais/edit.blade.php
@extends('layouts.dashboard')


@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('profissionais.update', $profissional->id) }}">
        @method('PUT')
        @csrf

        <h3>Atualizar profissional ({{ $profissional->nome }})</h3>
        
        @include('dashboard.cadastros.profissionais._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Atualizar</button>
    </form>


@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/profissional/create.js') }}"></script>
    <script>
        $(document).ready(function() {
            
            // Cor da agenda
            $("#color-picker").spectrum({
                color: @json($profissional->cor_agenda),
                preferredFormat: "hex",
                showPaletteOnly: true,
                palette: [
                    ["#d50000","#e67c73","#f4511e","#f6bf26","#33b679","#0b8043","#039be5","#3f51b5"],
                    ["#7986cb","#8e24aa","#616161"],
                ]
            });

            // Pre seleciona os servicos
            $('#servicos').val(@json($servicosSelecionados)).trigger('change');

        });
    </script>
@endsection

resources/views/dashboard/cadastros/profissionais/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <div class="d-flex justify-content-between w-100">
        <div>
            <h3>Profissionais</h3>
            <p>Número de Profissionais: {{ count($profissionais) }}</p>
        </div>
        <div>
            <a href="{{ route('profissionais.create') }}" class="btn btn-light btn-tool add">Adicionar um Profissional</a>
        </div>
    </div>

    @livewire('lista-profissionais')

    <!-- Modal -->
    <div class="modal fade modal-view" id="modal-profissional" tabindex="-1" role="dialog" aria-labelledby="modal-profissional-label"
    aria-hidden="true">
        {{-- Preenchido com AJAX --}}
    </div>

@endsection

@section('scripts')
    @livewireAssets
    <script src="{{ asset('js/dashboard/cadastros/profissional/index.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/profissionais/modal-profissional.blade.php
<div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="modal-profissional-label"><span class="font-weight-bold">{{ $profissional->nome }} </span> <span>(Profissional desde {{ date('d/m/Y', $profissional->created_at->timestamp) }})</span></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="">
                <div class="row">

                    <div class="col">

                        <h5 class="header">Informações Básicas</h5>
                        <div class="row info">
                            <div class="col font-weight-bold">Email</div>
                            <div class="col">{{ $profissional->email }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">CPF</div>
                            <div class="col">{{ $profissional->cpf }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">RG</div>
                            <div class="col">{{ $profissional->rg }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Telefone Celular</div>
                            <div class="col">{{ $profissional->telefone_celular }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Telefone Residencial</div>
                            <div class="col">{{ $profissional->telefone_residencial }}</div>
                        </div>

                        <h5 class="header mt-4">Informações Adicionais</h5>
                        <div class="row info">
                            <div class="col font-weight-bold">Horário de Entrada</div>
                            <div class="col">{{ $profissional->horario_entrada }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Horário de Saída</div>
                            <div class="col">{{ $profissional->horario_saida }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Cor na Agenda</div>
                            <div class="col">
                                <span class="cor-agenda-profissional" style="background-color: {{ $profissional->cor_agenda }};"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <h5 class="header">Informações de Endereço</h5>
                        <div class="row info">
                            <div class="col font-weight-bold">Cidade</div>
                            <div class="col">{{ $profissional->cidade->nome }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Estado</div>
                            <div class="col">{{ $profissional->cidade->estado->nome }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">CEP</div>
                            <div class="col">{{ $profissional->cep }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Bairro</div>
                            <div class="col">{{ $profissional->bairro }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Rua</div>
                            <div class="col">{{ $profissional->rua }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Número</div>
                            <div class="col">{{ $profissional->numero_rua }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Complemento</div>
                            <div class="col">{{ $profissional->complemento_rua }}</div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-light" data-dismiss="modal">Fechar</button>
        </div>
    </div>
</div>