routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->check())
        return redirect()->route('dashboard.index');

    return redirect()->route('login');
});

/**
 * AUTHENTICATION ROUTES
 */
Auth::routes();

/**
 * PAGES ROUTES
 */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

/**
 * ROTAS DE CADASTRO
 */

// Clientes
Route::resource('clientes', 'ClienteController');

// Profissionais
Route::resource('profissionais', 'ProfissionalController');

// Serviços
Route::resource('servicos', 'ServicoController');

// Produtos
Route::resource('produtos', 'ProdutoController');

// Pacotes
Route::resource('pacotes', 'PacoteController');

// Comandas
Route::resource('comandas', 'ComandaController');

/**
 * ROTAS DA AGENDA
 */
Route::prefix('agenda')->group(function() {

    Route::get('', 'AgendaController@index')->name('agenda.index');
    Route::get('/calendario', 'AgendaController@calendario')->name('agenda.calendario');
    Route::get('/novo-agendamento', 'AgendaController@novoAgendamento')->name('agenda.novoAgendamento');

});

/**
 * ROTAS DE AGENDAMENTO
 */
Route::resource('agendamentos', 'AgendamentoController');

/**
 * ROTAS DE AJAX
 */
Route::namespace('Ajax')->prefix('ajax')->group(function() {

    // Clientes
    Route::post('/modalInformacoesCliente', 'AjaxController@modalInformacoesCliente');

    // Profissionais
    Route::post('/modalInformacoesProfissional', 'AjaxController@modalInformacoesProfissional');

    // Serviços
    Route::post('/modalInformacoesServico', 'AjaxController@modalInformacoesServico');

    // Pacote
    Route::post('/modalInformacoesPacote', 'AjaxController@modalInformacoesPacote');
    
    // Agenda
    Route::post('/profissionaisDeUmServico', 'AjaxController@profissionaisDeUmServico');
    Route::post('/recuperarClientes', 'AjaxController@recuperarClientes');
    Route::post('/modalAgendamento', 'AjaxController@modalAgendamento');
    Route::post('/horariosDisponiveisDeUmProfissional', 'AjaxController@horariosDisponiveisDeUmProfissional');
    Route::post('/realizarAgendamento', 'AjaxController@realizarAgendamento');

});

use App\Agendamento;
use App\Profissional;
use App\Servico;
use Carbon\Carbon;

Route::get('/teste', function() {

    $idProfissional = 4;
    $idServico = 7;
        
    /**
     * Cria um vetor de horas (https://surniaulula.com/2016/lang/php/php-create-an-array-of-hours/)
     */
    function get_hours_range( $start = 0, $end = 86400, $step = 3600, $format = 'g:i a', $boolean = true ) {
        $times = array();
        for ( $i = 0; $i <= 6; $i++ ) { 
            foreach ( range( $start, $end, $step ) as $timestamp ) {
                $hour_mins = gmdate( 'H:i', $timestamp );
                $times[$i][$hour_mins] = $boolean;
            }
        }
        return $times;
    }

    /**
     * Recupera o inicio dessa semana
     */
    function primeiroDiaSemana($week, $year) {
        $dto = new DateTime();
        $dto->setISODate($year, $week);
        return $dto;
    }

    // Lista de horários das 10:00 às 18:00
    $horariosSemana = get_hours_range(36000, 64800, 900, 'g:i a', true);
    $limite = DateTime::createFromFormat('H:i', '18:00');

    // Lista de agendamentos
    $agendamentos = Agendamento::where('id_profissional', $idProfissional)->get();

    // Retorna apenas os agendamentos da semana atual
    $agendamentos = $agendamentos->filter(function($ag) {
        $inicio = new DateTime($ag->inicio);
        $semana = $inicio->format('W');
        $essaSemana = date('W');
        return $semana == $essaSemana; 
    });

    /**
     * Primeiro loop para marcar horários ocupados
     */
    foreach ($agendamentos as $ag) {
        
        $inicio = new DateTime($ag->inicio);    // DateTime de início do agendamento
        $fim = new DateTime($ag->fim);          // DateTime de fim do agendamento
        $dia = $inicio->format('N') - 1;        // Representação numérica do dia da semana (0: Segunda, 1: Terça,..., 5: Sábado, 6: Domingo)

        $atual = clone $inicio;
        while ($atual <= $fim) {
            $horario = $atual->format("H:i");
            $horariosSemana[$dia][$horario] = false;      // Marca o horário como ocupado
            $atual->modify("+15 minutes");          // Avança 15 minutos
        }

    }

    $tempo_execucao = Servico::find($idServico)->tempo_execucao_em_minutos;
    $horariosDisponiveis = get_hours_range(36000, 64800, 900, 'g:i a', false);

    /**
     * Segundo loop para verificar disponibilidade
     */
    foreach ($horariosSemana as $dia => $horarios) {
        foreach ($horarios as $horario => $disponivel) {
            
            $atual = DateTime::createFromFormat('H:i', $horario);
            $hAtual = $atual->format('H:i');
            $fim = clone $atual;
            $fim->modify("+" . $tempo_execucao . " minutes");
            $hFim = $fim->format('H:i');

            /**
             * Verifica se o horário atual está disponível e o horário depois do tempo
             * de execução do serviço está disponível. Se sim, este é um horário disponível
             */
            if ($horariosSemana[$dia][$hAtual] == true AND $fim <= $limite AND $horariosSemana[$dia][$hFim] == true) {
                $horariosDisponiveis[$dia][$hAtual] = true;
            }
        }
    }

    // Dias da semana
    $segunda = primeiroDiaSemana(date('W'), date('Y'));

    return view('dashboard.agenda.tabela-horarios-disponiveis', [
        'horariosDisponiveis' => $horariosDisponiveis,
        'segunda' => $segunda,
    ]);

});

app/Servico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Servico extends Model
{
    /**
     * Relacionamentos
     */
    public function profissionais() {
        return $this->belongsToMany('App\Profissional', 'profissional_servico', 'id_servico', 'id_profissional');
    }
}

app/Http/Controllers/ServicoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Servico;

class ServicoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.cadastros.servicos.index', [
            'servicos' => Servico::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.cadastros.servicos.create', [
            'servico' => new Servico,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /**
         * Criar novo servico
         */
        $servico = new Servico;
        $servico->nome = request('nome');
        $servico->preco = request('preco');
        $servico->comissao = request('comissao');
        $servico->tempo_execucao_em_minutos = request('tempo-execucao');
        $servico->pontos = request('pontos');
        $servico->duracao_em_dias = request('duracao');
        $servico->enviar_notificacao_cliente = request('enviar-notificacao') ? true : false;
        $servico->ativo = request('ativo') ? true : false;
        $servico->observacoes = request('observacoes');
        $servico->save();

        return redirect()->route('servicos.index')->with('success', 'Serviço cadastrado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('dashboard.cadastros.servicos.edit', [
            'servico' => Servico::find($id),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /**
         * Atualizar servico
         */
        $servico = Servico::find($id);
        $servico->nome = request('nome');
        $servico->preco = request('preco');
        $servico->comissao = request('comissao');
        $servico->tempo_execucao_em_minutos = request('tempo-execucao');
        $servico->pontos = request('pontos');
        $servico->duracao_em_dias = request('duracao');
        $servico->enviar_notificacao_cliente = request('enviar-notificacao') ? true : false;
        $servico->ativo = request('ativo') ? true : false;
        $servico->observacoes = request('observacoes');
        $servico->save();

        return redirect()->route('servicos.index')->with('success', 'Serviço atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        /**
         * Remove o servico
         */
        $servico = Servico::find($id);
        $servico->delete();

        return redirect()->route('servicos.index')->with('success', 'Serviço removido com sucesso');
    }
}

resources/views/dashboard/cadastros/servicos/_form.blade.php
<div class="row mt-5">
        
    <div class="col">
        <h5>Informações Básicas</h5>

        <div class="form-group mt-3">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do serviço" autocomplete="new" value="{{ $servico->nome }}" required>
        </div>

        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="preco">Preço</label>
                    <input type="number" step="0.01" min="0.01" class="form-control" id="preco" name="preco" placeholder="Preço do serviço" autocomplete="new" value="{{ $servico->preco }}" required>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="comissao">Comissão (%)</label>
                    <input type="number" step="0.1" class="form-control" id="comissao" name="comissao" placeholder="Comissão sobre o serviço" autocomplete="new" value="{{ $servico->comissao }}" required>
                </div>
            </div>
        </div>
        
        <div class="row mt-3">
            <div class="col">
                <div class="form-group">
                    <label for="tempo-execucao">Tempo de Execução (em minutos)</label>
                    <select class="browser-default custom-select" id="tempo-execucao" name="tempo-execucao">
                        <option></option>
                        <option value="15" {{ $servico->tempo_execucao_em_minutos == 15 ? 'selected' : '' }}>15 minutos</option>
                        <option value="30" {{ $servico->tempo_execucao_em_minutos == 30 ? 'selected' : '' }}>30 minutos</option>
                        <option value="45" {{ $servico->tempo_execucao_em_minutos == 45 ? 'selected' : '' }}>45 minutos</option>
                        <option value="60" {{ $servico->tempo_execucao_em_minutos == 60 ? 'selected' : '' }}>60 minutos</option>
                        <option value="75" {{ $servico->tempo_execucao_em_minutos == 75 ? 'selected' : '' }}>75 minutos</option>
                        <option value="90" {{ $servico->tempo_execucao_em_minutos == 90 ? 'selected' : '' }}>90 minutos</option>
                    </select>
                </div>
            </div>

            <div class="col">
                <div class="form-group">
                    <label for="pontos">Pontos</label>
                    <input type="number" class="form-control" id="pontos" name="pontos" placeholder="Pontos do serviço" autocomplete="new" value="{{ $servico->pontos }}" required>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="duracao">Duração (em dias)</label>
            <input type="number" class="form-control" id="duracao" name="duracao" placeholder="Duração média do serviço em dias" autocomplete="new" value="{{ $servico->duracao_em_dias }}" required>
        </div>

        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="enviar-notificacao" name="enviar-notificacao" {{ $servico->enviar_notificacao_cliente ? 'checked' : '' }}>
            <label class="custom-control-label" for="enviar-notificacao">Enviar notificações ao cliente após esse período</label>
        </div>
    
        <label class="d-block mt-3">O serviço está ativo?</label>
        <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="ativo" name="ativo" {{ $servico->ativo ? 'checked' : '' }}>
            <label class="custom-control-label" for="ativo"></label>
        </div>
        
    </div>
    <div class="col">
        <h5>Informações Extras</h5>

        {{-- <div class="form-group mt-3">
            <label for="produtos">Produtos</label>
            <select class="browser-default custom-select" id="produtos" name="produtos">
                <option>Produtos recomendados</option>
            </select>
        </div> --}}

        <div class="form-group mt-3">
            <label for="observacoes">Observações</label>
            <textarea class="form-control rounded-1" id="observacoes" rows="3" placeholder="Observações sobre o serviço">{{ $servico->observacoes }}</textarea>
        </div>
    </div>

</div>

resources/views/dashboard/cadastros/servicos/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('servicos.store') }}">
        @csrf

        <h3>Cadastro de Serviços</h3>
        
        @include('dashboard.cadastros.servicos._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Cadastrar</button>
    </form>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/servico/create.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/servicos/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('servicos.update', $servico->id) }}">
        @method('PUT')
        @csrf

        <h3>Editar serviço ({{ $servico->nome }})</h3>
        
        @include('dashboard.cadastros.servicos._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Editar</button>
    </form>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/servico/create.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/servicos/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
<div class="d-flex justify-content-between w-100">
        <div>
            <h3>Serviços</h3>
            <p>Número de Serviços: {{ count($servicos) }}</p>
        </div>
        <div>
            <a href="{{ route('servicos.create') }}" class="btn btn-light btn-tool add">Adicionar um serviço</a>
        </div>
    </div>

    @if (count($servicos) > 0)
        <table class="table table-cadastro">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Ativo</th>
                    <th>Preço</th>
                    <th>Tempo de Execução (min)</th>
                    <th>Pontos</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($servicos as $servico)
                    <tr>
                        <td>{{ $servico->nome }}</td>
                        <td>{{ $servico->ativo ? 'Sim' : 'Não' }}</td>
                        <td>{{ $servico->preco }}</td>
                        <td>{{ $servico->tempo_execucao_em_minutos }}</td>
                        <td>{{ $servico->pontos }}</td>
                        <td class="td-actions">
                            <button class="btn-action view" data-id-servico="{{ $servico->id }}"><i class="fas fa-eye"></i></button>
                            <a href="{{ route('servicos.edit', $servico->id) }}" class="btn-action"><i class="fas fa-pencil-alt"></i></a>
                            <form method="POST" action="{{ route('servicos.destroy', $servico->id) }}" class="remove-form" onsubmit="return confirm('Você realmente quer remover este serviço?');">
                                @method('DELETE')
                                @csrf
                                <button class="btn-action"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="alert alert-info" role="alert">
            Nenhum serviço foi cadastrado ainda. Você pode cadastrar um clicando no botão acima.
        </div>
    @endif

    <!-- Modal -->
    <div class="modal fade modal-view" id="modal-servico" tabindex="-1" role="dialog" aria-labelledby="modal-servico-label"
    aria-hidden="true">
        {{-- Preenchido com AJAX --}}
    </div>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/servico/index.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/servicos/modal-servico.blade.php
<div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="modal-servico-label"><span class="font-weight-bold">{{ $servico->nome }} </span> <span>(Adicionado em {{ date('d/m/Y', $servico->created_at->timestamp) }})</span></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <div class="">
                <div class="row">

                    <div class="col">
                        <h5 class="header">Informações Básicas</h5>
                        <div class="row info">
                            <div class="col font-weight-bold">Ativo</div>
                            <div class="col">{{ $servico->ativo ? 'Sim' : 'Não' }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Preço</div>
                            <div class="col">{{ $servico->preco }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Tempo de Execução (em minutos)</div>
                            <div class="col">{{ $servico->tempo_execucao_em_minutos }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Tempo de Duração (em dias)</div>
                            <div class="col">{{ $servico->duracao_em_dias }}</div>
                        </div>
                    </div>

                    <div class="col">
                        <h5 class="header">Informações Adicionais</h5>
                        <div class="row info">
                            <div class="col font-weight-bold">Taxa de Comissão (%)</div>
                            <div class="col">{{ $servico->comissao }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Pontuação</div>
                            <div class="col">{{ $servico->pontos }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Observações</div>
                            <div class="col">{{ $servico->observacoes }}</div>
                        </div>
                        <div class="row info">
                            <div class="col font-weight-bold">Enviar Notificação ao Cliente?</div>
                            <div class="col">{{ $servico->enviar_notificacao_cliente ? 'Sim' : 'Não' }}</div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-light" data-dismiss="modal">Fechar</button>
        </div>
    </div>
</div>