routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->check())
        return redirect()->route('dashboard.index');

    return redirect()->route('login');
});

/**
 * AUTHENTICATION ROUTES
 */
Auth::routes();

/**
 * PAGES ROUTES
 */
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');

/**
 * ROTAS DE CADASTRO
 */

// Clientes
Route::resource('clientes', 'ClienteController');

// Profissionais
Route::resource('profissionais', 'ProfissionalController');

// Serviços
Route::resource('servicos', 'ServicoController');

// Produtos
Route::resource('produtos', 'ProdutoController');

// Pacotes
Route::resource('pacotes', 'PacoteController');

// Comandas
Route::resource('comandas', 'ComandaController');

/**
 * ROTAS DA AGENDA
 */
Route::prefix('agenda')->group(function() {

    Route::get('', 'AgendaController@index')->name('agenda.index');
    Route::get('/calendario', 'AgendaController@calendario')->name('agenda.calendario');
    Route::get('/novo-agendamento', 'AgendaController@novoAgendamento')->name('agenda.novoAgendamento');

});

/**
 * ROTAS DE AGENDAMENTO
 */
Route::resource('agendamentos', 'AgendamentoController');

/**
 * ROTAS DE AJAX
 */
Route::namespace('Ajax')->prefix('ajax')->group(function() {

    // Clientes
    Route::post('/modalInformacoesCliente', 'AjaxController@modalInformacoesCliente');

    // Profissionais
    Route::post('/modalInformacoesProfissional', 'AjaxController@modalInformacoesProfissional');

    // Serviços
    Route::post('/modalInformacoesServico', 'AjaxController@modalInformacoesServico');

    // Pacote
    Route::post('/modalInformacoesPacote', 'AjaxController@modalInformacoesPacote');
    
    // Agenda
    Route::post('/profissionaisDeUmServico', 'AjaxController@profissionaisDeUmServico');
    Route::post('/recuperarClientes', 'AjaxController@recuperarClientes');
    Route::post('/modalAgendamento', 'AjaxController@modalAgendamento');
    Route::post('/horariosDisponiveisDeUmProfissional', 'AjaxController@horariosDisponiveisDeUmProfissional');
    Route::post('/realizarAgendamento', 'AjaxController@realizarAgendamento');

});

use App\Agendamento;
use App\Profissional;
use App\Servico;
use Carbon\Carbon;

Route::get('/teste', function() {

    $idProfissional = 4;
    $idServico = 7;
        
    /**
     * Cria um vetor de horas (https://surniaulula.com/2016/lang/php/php-create-an-array-of-hours/)
     */
    function get_hours_range( $start = 0, $end = 86400, $step = 3600, $format = 'g:i a', $boolean = true ) {
        $times = array();
        for ( $i = 0; $i <= 6; $i++ ) { 
            foreach ( range( $start, $end, $step ) as $timestamp ) {
                $hour_mins = gmdate( 'H:i', $timestamp );
                $times[$i][$hour_mins] = $boolean;
            }
        }
        return $times;
    }

    /**
     * Recupera o inicio dessa semana
     */
    function primeiroDiaSemana($week, $year) {
        $dto = new DateTime();
        $dto->setISODate($year, $week);
        return $dto;
    }

    // Lista de horários das 10:00 às 18:00
    $horariosSemana = get_hours_range(36000, 64800, 900, 'g:i a', true);
    $limite = DateTime::createFromFormat('H:i', '18:00');

    // Lista de agendamentos
    $agendamentos = Agendamento::where('id_profissional', $idProfissional)->get();

    // Retorna apenas os agendamentos da semana atual
    $agendamentos = $agendamentos->filter(function($ag) {
        $inicio = new DateTime($ag->inicio);
        $semana = $inicio->format('W');
        $essaSemana = date('W');
        return $semana == $essaSemana; 
    });

    /**
     * Primeiro loop para marcar horários ocupados
     */
    foreach ($agendamentos as $ag) {
        
        $inicio = new DateTime($ag->inicio);    // DateTime de início do agendamento
        $fim = new DateTime($ag->fim);          // DateTime de fim do agendamento
        $dia = $inicio->format('N') - 1;        // Representação numérica do dia da semana (0: Segunda, 1: Terça,..., 5: Sábado, 6: Domingo)

        $atual = clone $inicio;
        while ($atual <= $fim) {
            $horario = $atual->format("H:i");
            $horariosSemana[$dia][$horario] = false;      // Marca o horário como ocupado
            $atual->modify("+15 minutes");          // Avança 15 minutos
        }

    }

    $tempo_execucao = Servico::find($idServico)->tempo_execucao_em_minutos;
    $horariosDisponiveis = get_hours_range(36000, 64800, 900, 'g:i a', false);

    /**
     * Segundo loop para verificar disponibilidade
     */
    foreach ($horariosSemana as $dia => $horarios) {
        foreach ($horarios as $horario => $disponivel) {
            
            $atual = DateTime::createFromFormat('H:i', $horario);
            $hAtual = $atual->format('H:i');
            $fim = clone $atual;
            $fim->modify("+" . $tempo_execucao . " minutes");
            $hFim = $fim->format('H:i');

            /**
             * Verifica se o horário atual está disponível e o horário depois do tempo
             * de execução do serviço está disponível. Se sim, este é um horário disponível
             */
            if ($horariosSemana[$dia][$hAtual] == true AND $fim <= $limite AND $horariosSemana[$dia][$hFim] == true) {
                $horariosDisponiveis[$dia][$hAtual] = true;
            }
        }
    }

    // Dias da semana
    $segunda = primeiroDiaSemana(date('W'), date('Y'));

    return view('dashboard.agenda.tabela-horarios-disponiveis', [
        'horariosDisponiveis' => $horariosDisponiveis,
        'segunda' => $segunda,
    ]);

});

app/Produto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    // Relacionamentos
    public function marca() {
        return $this->belongsTo('App\Marca', 'id_marca', 'id');
    }
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Marca;
use App\Produto;

class ProdutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dd(Produto::all());
        return view('dashboard.cadastros.produtos.index', [
            'produtos' => Produto::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.cadastros.produtos.create', [
            'produto' => new Produto,
            'marcas' => Marca::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produto = new Produto;
        $produto->nome = request('nome');

        // Atribui a marca
        $id_marca = request('marca');
        if (!is_numeric($id_marca)) {
            // Cria nova marca
            $marca = new Marca;
            $marca->nome = $id_marca;
            $marca->save();
            $id_marca = $marca->id;
        }
        $produto->id_marca = $id_marca;

        $produto->preco = request('preco');
        $produto->pontos = request('pontos');
        $produto->save();

        return redirect()->route('produtos.index')->with('success', 'Produto cadastrado com sucesso');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('dashboard.cadastros.produtos.edit', [
            'produto' => Produto::find($id),
            'marcas' => Marca::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $produto = Produto::find($id);
        $produto->nome = request('nome');
        
        // Atribui a marca
        $id_marca = request('marca');
        if (!is_numeric($id_marca)) {
            // Cria nova marca
            $marca = new Marca;
            $marca->nome = $id_marca;
            $marca->save();
            $id_marca = $marca->id;
        }
        $produto->id_marca = $id_marca;

        $produto->preco = request('preco');
        $produto->pontos = request('pontos');
        $produto->save();

        return redirect()->route('produtos.index')->with('success', 'Produto atualizado com sucesso');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $produto = Produto::find($id);
        $produto->delete();

        return redirect()->route('produtos.index')->with('success', 'Produto removido com sucesso');
    }
}

resources/views/dashboard/cadastros/produtos/_form.blade.php
<div class="row mt-5">
    <div class="col-6">
        <h5>Informações Básicas</h5>

        <div class="form-group mt-3">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do produto" autocomplete="new" required value="{{ $produto->nome }}">
        </div>

        <div class="form-group">
            <label for="marca">Marca</label>
            <select class="browser-default custom-select" id="marca" name="marca" required>
                <option></option>
                @foreach ($marcas as $marca)
                    <option value="{{ $marca->id }}" {{ $produto->id_marca == $marca->id ? 'selected' : '' }}>{{ $marca->nome }}</option>
                @endforeach
            </select>
        </div>
        
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="preco">Preço</label>
                    <input type="number" step="0.01" min="1" class="form-control" id="preco" name="preco" placeholder="Preço do produto" autocomplete="new" required value="{{ $produto->preco }}">
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="pontos">Pontos</label>
                    <input type="number" class="form-control" id="pontos" name="pontos" placeholder="Pontos" autocomplete="new" required value="{{ $produto->pontos }}">
                </div>
            </div>
        </div>
    </div>

</div>

resources/views/dashboard/cadastros/produtos/create.blade.php
@extends('layouts.dashboard')


@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('produtos.store') }}">
        @csrf

        <h3>Cadastro de Produtos</h3>
        
        @include('dashboard.cadastros.produtos._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Cadastrar</button>
    </form>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/produto/create.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/produtos/edit.blade.php
@extends('layouts.dashboard')


@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <form method="POST" action="{{ route('produtos.update', $produto->id) }}">
        @method('PUT')
        @csrf

        <h3>Edição de Produto ({{ $produto->nome }})</h3>
        
        @include('dashboard.cadastros.produtos._form')
        
        <button type="submit" class="btn btn-primary btn-tool float-right mt-4">Editar</button>
    </form>

@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/produto/create.js') }}"></script>
@endsection

resources/views/dashboard/cadastros/produtos/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('dashboard-sidebar')
    @include('dashboard.components._dashboard-sidebar')
@endsection

@section('dashboard-content')
    
    <div class="d-flex justify-content-between w-100">
        <div>
            <h3>Produtos</h3>
            <p>Número de Produtos: {{ count($produtos) }}</p>
        </div>
        <div>
            <a href="{{ route('produtos.create') }}" class="btn btn-light btn-tool add">Adicionar um Produto</a>
        </div>
    </div>

    @if (count($produtos) > 0)
        <table class="table table-cadastro">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Marca</th>
                    <th>Preço</th>
                    <th>Pontos</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($produtos as $produto)
                    <tr>
                        <td>{{ $produto->nome }}</td>
                        <td>{{ $produto->marca ? $produto->marca->nome : '-' }}</td>
                        <td>{{ $produto->preco }}</td>
                        <td>{{ $produto->pontos }}</td>
                        <td class="td-actions">
                            <a href="{{ route('produtos.edit', $produto->id) }}" class="btn-action"><i class="fas fa-pencil-alt"></i></a>
                            <form method="POST" action="{{ route('produtos.destroy', $produto->id) }}" class="remove-form" onsubmit="return confirm('Você realmente quer remover este produto?');">
                                @method('DELETE')
                                @csrf
                                <button class="btn-action"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else 
        <div class="alert alert-info" role="alert">
            Nenhum produto foi cadastrado ainda. Você pode cadastrar um clicando no botão acima.
        </div>
    @endif


@endsection

@section('scripts')
    <script src="{{ asset('js/dashboard/cadastros/produto/index.js') }}"></script>
@endsection